version: "3"
services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
      - SERVER_PORT=8888
      - MONGODB_URI=mongodb://db:27017/annotator
    links:
      - db
    depends_on:
      - db

  db:
    build: 
        context: https://github.com/eugeniomazzone/genome-nexus-importer.git
        dockerfile: Dockerfile_dog
    environment:
      - REF_ENSEMBL_VERSION=cfa_ensembl104
      - SPECIES=canis_lupus_familiaris
    restart: always

  vep:
    build:
      context: ../genome-nexus-vep
      dockerfile: Dockerfile
    environment:
      - VEP_ASSEMBLY=${VEP_ASSEMBLY}
    restart: always
    ports:
      - "6060:8080"
    volumes:
      - ${VEP_CACHE}:/opt/vep/.vep/
